"""progress

Revision ID: ac6e3bc5f281
Revises: 4047705b7fab
Create Date: 2024-10-17 03:15:05.266359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6e3bc5f281'
down_revision = '4047705b7fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_queue', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
