version: '3'
services:
  web:
    build: web/.
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - ./shared:/app/shared  # Shared volume for file access
      - ./spotify_cache:/app/.cache  # Mount the local cache into the container
    env_file:
      - .env
    depends_on:
      - celery_worker
      - redis
  celery_worker:
    build: web/.  # Reuse the same image, but run Celery worker instead of the web app
    command: /bin/bash -c "/app/replace_zotify_credentials.sh && celery -A celery_app worker --loglevel=info"
    mem_limit: 2g
    cpus: "1.0"
    volumes:
      - ./shared:/app/shared  # Shared volume for file access
      - ./spotify_cache:/app/.cache
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  spleeter:
    build: spleeter/.
    ports:
      - "5001:5001"  # Expose the API port
    volumes:
      - ./shared:/app/shared  # Shared volume for file access
