version: '3'
services:
  web:
    build: web/.
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/app/shared  # Shared volume for file access
    env_file:
      - .env
    depends_on:
      - spleeter
  spleeter:
    build: spleeter/.
    ports:
      - "5001:5001"  # Expose the API port
    volumes:
      - ./shared:/app/shared  # Shared volume for file access
